name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd /home/runner/work/moreticket/
          rm -r moreticket/.git* moreticket/tools
          tar -zcvf moreticket-${{ github.ref_name }}.tgz moreticket

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: moreticket-${{ github.ref_name }}.tgz
          path: /home/runner/work/moreticket/moreticket-${{ github.ref_name }}.tgz
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/moreticket/moreticket-${{ github.ref_name }}.tgz
          body: "New release is available"
          name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
